### ISSUE TITLE
Reserved_XXX_Slot compatibility issue

### ISSUE THREAD

**Issue by SergeiBabko** [FluffyFishGames/AdvancedCompany#105]
AdvancedCompany v.1.0.149

[ReservedWeaponSlot v.1.0.8](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedWeaponSlot/)
[ReservedWalkieSlot v.1.6.2](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedWalkieSlot/)
[ReservedFlashlightSlot v.1.6.3](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedFlashlightSlot/)
[ReservedSprayPaintSlot v.1.0.7](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedSprayPaintSlot/)
[ReservedKeySlot v.1.0.4](https://thunderstore.io/c/lethal-company/p/RogueCodes/ReservedKeySlot/)

and other Reserved_XXX_Slot mods

It would be highly appreciated if you could implement something akin to the provided modes within your AdvancedCompany, similar to how you organized the Clothing slots.

Currently, the slots are functional, but they are all linked in a single row at the bottom of the screen, making it challenging to navigate between them and manage clothing items effectively.

**Comment by YoBii** [comment]
These mods have conflicting philosophies.

Instead of getting free reserved slots with AC you can unlock additional slots for these items by leveling carry bags perk.
You could also increase the base amount of slots ofc.
Then there's also gear or clothing slots that are essentially reserved slot with the twist of you having to invest credits into the gear and risking losing them. 

The dev has previously stated that fully integrating reserved slots would require a lot of time invest as the entire inventory code would have to be rewritten and it's nothing he envisions for his mod thus it's very low priority.

Just fyi

**Comment by SergeiBabko** [comment]
> These mods have conflicting philosophies.
> 
> Instead of getting free reserved slots with AC you can unlock additional slots for these items by leveling carry bags perk. You could also increase the base amount of slots ofc. Then there's also gear or clothing slots that are essentially reserved slot with the twist of you having to invest credits into the gear and risking losing them.
> 
> The dev has previously stated that fully integrating reserved slots would require a lot of time invest as the entire inventory code would have to be rewritten and it's nothing he envisions for his mod thus it's very low priority.
> 
> Just fyi

I've already embraced this philosophy, and it sounds quite reasonable. However, it would still be fantastic to have the option to swiftly drop all inventory loots in one go, akin to the functionality implemented in the [QuickDrop](https://thunderstore.io/c/lethal-company/p/Nases/Quick_Drop/) mod ;)
